<?php
define('CLIENT_ID','YOUR-TWITTER-APP-CLIENT-ID');
define('CLIENT_SECRET','YOUR-TWITTER-APP-CLIENT-SECRET');
define('ACCESS_TOKEN','YOUR-TWITTER-APP-ACCESS-TOKEN');


define('WEBSITE_URL','YOUR-SITE-URL');
define('REDIRECT_URI','YOUR-SITE-URL');
define('CALLBACK_URL','YOUR-CALLBACK-URL');
